epee: partially revert 183c29b5 to fix linking errors
On Linux Mint 21.3, g++ Ubuntu 11.4.0-1ubuntu1~22.04, I get linking error for an undefined reference to `epee::string_tools::trim_right`. This PR reverts the changes
to epee_readline.cpp in commit 183c29b5, which turns a `boost::trim_right` callsite into an `epee::string_tools::trim_right` callsite.